// Chaque projet garde sa propre identité : police du titre, fond, encre et accent de son site.
// statut : "ligne" | "pret" | "dev" | "maquette" | "local" | "archive"
// groupe : "vitrines" | "boutiques" | "crypto"
window.PROJETS = [
  {    id: "fd", nom: "École Frédéric Dardailler", groupe: "vitrines", date: "2026-08", statut: "ligne",
    url: "https://fd-energeticien.com",
    resume: "École de soins énergétiques à Montauban. Onze formations (pendule, radiesthésie, Lahochi, diapasons…) à distance ou en présentiel, avec inscription, paiement et boutique en ligne.",
    stack: "Vanilla, Cloudflare Pages Functions, Stripe",
    police: "'IM Fell English', serif", italique: true,
    fond: "#EDE3CF", encre: "#3B2A1A", accent: "#9A7424", palette: ["#EDE3CF", "#3B2A1A", "#C9A24A", "#B88746"],
    captures: ["fd-energeticien"],
  },
  {    id: "natacha", nom: "Natacha Fourrageat", groupe: "vitrines", date: "2026-06", statut: "ligne",
    url: "https://natachafourrageat.com",
    resume: "Site d'une naturopathe et monitrice d'auto-école au Pays basque : émotions, parentalité, conduite, et ses livres.",
    stack: "React précompilé avec esbuild, Cloudflare Pages, Resend",
    police: "'Caveat', cursive", graisse: 600, echelle: 1.18,
    fond: "#FBEEE6", encre: "#1F4659", accent: "#1F4659", palette: ["#F4D8C8", "#1F4659", "#7DB3D1", "#B5896A"],
    captures: ["natacha"],
  },
  {    id: "myclothes", nom: "My Clothes", groupe: "boutiques", date: "2026-05", statut: "ligne",
    url: "https://my-clothes.pages.dev",
    resume: "Boutique de vêtements : maillots, t-shirts et sweats, panier, paiement Stripe et espace d'administration des commandes.",
    stack: "React sans build, Cloudflare Pages Functions, Stripe, KV",
    police: "'Instrument Serif', serif", italique: true,
    fond: "#141414", encre: "#F4F1EA", accent: "#FF3B00", palette: ["#F4F1EA", "#0A0A0A", "#FF3B00"],
    captures: ["myclothes"],
  },
  {    id: "airdrop", nom: "Airdrop Formation", groupe: "vitrines", date: "2026-05", statut: "ligne",
    url: "https://airdrop-formation.pages.dev",
    resume: "Formation payante en français, en anglais et en espagnol pour farmer son premier airdrop crypto : 6 modules, calculateur, fiscalité, delta neutral et certificat.",
    stack: "Vanilla, Three.js, Cloudflare Pages Functions, Stripe, Resend",
    police: "'Space Grotesk', sans-serif", graisse: 700,
    fond: "#131210", encre: "#F3EDE2", accent: "#FFB000", palette: ["#131210", "#FFB000", "#FF6B00"],
    captures: ["airdrop"],
  },
  {    id: "starconnect", nom: "StarConnect Solutions", groupe: "vitrines", date: "2026-04", statut: "ligne",
    url: "https://starconnectsolutions.com",
    resume: "Entreprise d'accès Internet par satellite Starlink pour les immeubles : services, réalisations, appels d'offres et recrutement, en plusieurs langues dont l'arabe et le bengali.",
    stack: "Vanilla, 9 pages, i18n maison",
    police: "'Montserrat', sans-serif", graisse: 700,
    fond: "#05080F", encre: "#E6EEF8", accent: "#4FC3F7", palette: ["#05080F", "#3B82F6", "#4FC3F7", "#FFB74D"],
    captures: ["starconnect"],
  },
  {    id: "aline", nom: "Aline Strhauss", groupe: "vitrines", date: "2026-08", statut: "pret",
    domaine: "aline-strhauss.com",
    resume: "Refonte du site d'une hypnothérapeute de Montauban : hypnose, arrêt du tabac, transgénérationnel, tarifs et prise de rendez-vous en ligne.",
    stack: "Vanilla, générateur build.js, Cloudflare Pages, Resend, Cal.com",
    police: "'Cormorant Garamond', serif", italique: true, graisse: 500,
    fond: "#EFEAE3", encre: "#3E4A3E", accent: "#7A5A1E", palette: ["#EFEAE3", "#3E4A3E", "#B4883F"],
    captures: ["aline"],
  },
  {    id: "lutece", nom: "Maison Lutèce", groupe: "vitrines", date: "2026-05", statut: "maquette",
    resume: "Démonstration d'un site d'hôtel-restaurant 4 étoiles dans le Marais : chambres, restaurant et bar, événements, coffrets et galerie, sur 12 pages.",
    stack: "Vanilla",
    police: "'Cormorant Garamond', serif", graisse: 600,
    fond: "#F6F1EA", encre: "#1A1A1A", accent: "#7F6431", palette: ["#F6F1EA", "#1A1A1A", "#9A7B3F"],
    captures: ["lutece"],
  },
  {    id: "nova", nom: "Nova", groupe: "crypto", date: "2026-09", statut: "dev",
    resume: "Néobanque qui rémunère vos euros. Connexion par e-mail, dépôt par carte ou SEPA ; en coulisses, l'épargne va dans un vault delta-neutre sur HyperEVM.",
    stack: "Vanilla multi-pages, Vite, îlot React pour Privy, worker Cloudflare D1",
    police: "'Archivo', sans-serif", graisse: 700,
    fond: "#E9E4DB", encre: "#17171A", accent: "#1FA955", palette: ["#E9E4DB", "#17171A", "#2FD96E"],
    captures: ["nova"],
  },
  {    id: "debats", nom: "debats.io", groupe: "crypto", date: "2026-05", statut: "dev",
    resume: "Application de débat philosophique autour des 17 notions de terminale : joutes Pour et Contre, notation, classement et cartes-philosophe.",
    stack: "React par CDN, sans build",
    police: "'Bricolage Grotesque', sans-serif", graisse: 700,
    fond: "#0F0E17", encre: "#F0EEFF", accent: "#A48BFF", palette: ["#08080D", "#8B6CFF", "#FF8A3D", "#3AD7E6"],
    captures: ["debats"],
  },
  {    id: "tradoor", nom: "Tradoor", groupe: "crypto", date: "2026-09", statut: "ligne",
    url: "https://tradoor0.xyz",
    resume: "Plateforme de bots de market making et de volume sur Hyperliquid, HIP-4, Trade.xyz, Extended, Nado et Bulk. Connexion par wallet, programme de points et de parrainage.",
    stack: "HTML, CSS et JS vanilla servis par un backend Python sur VPS",
    police: "'Instrument Serif', serif", italique: true,
    fond: "#0A0808", encre: "#F5EEE8", accent: "#FF6B2C", palette: ["#0A0808", "#FF6B2C", "#FF9E5C", "#35F0C2"],
    captures: ["tradoor", "tradoor-app"],
  },
];
